openapi: 3.2.0
info:
  title: ClickUp API v2 Reference Users API
  description: The ClickUp API enables you to programmatically access and manage your ClickUp resources.
  contact: {}
  version: '2.0'
servers:
- url: https://api.clickup.com/api
  description: ClickUp
  variables: {}
security:
- Authorization_Token: []
tags:
- name: Users
paths:
  /v2/team/{team_id}/user:
    parameters: []
    post:
      summary: Invite User To Workspace
      tags:
      - Users
      description: 'Invite someone to join your Workspace as a member. To invite someone as a guest, use the Invite Guest endpoint.\

        \

        ***Note:** This endpoint is only available to Workspaces on our Enterprise Plan.*'
      operationId: InviteUserToWorkspace
      parameters:
      - name: team_id
        in: path
        description: Workspace ID
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 123
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              title: InviteUserToWorkspacerequest
              required:
              - email
              - admin
              type: object
              properties:
                email:
                  type: string
                admin:
                  type: boolean
                custom_role_id:
                  type: integer
                  contentEncoding: int32
              examples:
              - email: user@example.com
                admin: true
                custom_role_id: 112233
            example:
              email: user@example.com
              admin: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                title: InviteUserToWorkspaceresponse
                required:
                - team
                type: object
                properties:
                  team:
                    title: Team3
                    required:
                    - id
                    - name
                    - color
                    - avatar
                    - members
                    - roles
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      color:
                        type: string
                      avatar:
                        type:
                        - string
                        - 'null'
                      members:
                        type: array
                        items:
                          title: Members5
                          required:
                          - user
                          - invited_by
                          type: object
                          properties:
                            user:
                              $ref: '#/paths/~1v2~1team~1{team_id}~1guest~1{guest_id}/put/responses/200/content/application~1json/schema/properties/guest/properties/user'
                            invited_by:
                              $ref: '#/paths/~1v2~1team~1{team_id}~1user~1{user_id}/get/responses/200/content/application~1json/schema/properties/member/properties/invited_by'
                          examples:
                          - user:
                              id: 184
                              username: null
                              email: user@example.com
                              color: null
                              profilePicture: null
                              initials: G
                              role: 2
                              custom_role:
                                id: 112233
                                name: admin custom
                              last_active: null
                              date_joined: null
                              date_invited: '1583358383412'
                            invited_by:
                              id: 183
                              color: '#827718'
                              username: Jerry
                              email: jerry@example.com
                              initials: J
                              profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                        description: ''
                      roles:
                        type: array
                        items:
                          title: Role
                          required:
                          - id
                          - name
                          - custom
                          type: object
                          properties:
                            id:
                              type: integer
                              contentEncoding: int32
                            name:
                              type: string
                            custom:
                              type: boolean
                            inherited_role:
                              type: integer
                              contentEncoding: int32
                          examples:
                          - id: 1
                            name: owner
                            custom: false
                        description: ''
                    examples:
                    - id: '333'
                      name: Team Name
                      color: '#8D00D4'
                      avatar: null
                      members:
                      - user:
                          id: 184
                          username: null
                          email: user@example.com
                          color: null
                          profilePicture: null
                          initials: G
                          role: 2
                          custom_role:
                            id: 112233
                            name: admin custom
                          last_active: null
                          date_joined: null
                          date_invited: '1583358383412'
                        invited_by:
                          id: 183
                          color: '#827718'
                          username: Jerry
                          email: jerry@example.com
                          initials: J
                          profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                      roles:
                      - id: 1
                        name: owner
                        custom: false
                      - id: 2
                        name: admin
                        custom: false
                      - id: 3
                        name: member
                        custom: false
                      - id: 4
                        name: guest
                        custom: false
                      - id: 998877
                        name: member custom
                        inherited_role: 3
                        custom: true
                      - id: 112233
                        name: admin custom
                        inherited_role: 2
                        custom: true
                      - id: 12345
                        name: guest custom
                        inherited_role: 4
                        custom: true
                examples:
                - team:
                    id: '333'
                    name: Team Name
                    color: '#8D00D4'
                    avatar: null
                    members:
                    - user:
                        id: 184
                        username: null
                        email: user@example.com
                        color: null
                        profilePicture: null
                        initials: G
                        role: 2
                        custom_role:
                          id: 112233
                          name: admin custom
                        last_active: null
                        date_joined: null
                        date_invited: '1583358383412'
                      invited_by:
                        id: 183
                        color: '#827718'
                        username: Jerry
                        email: jerry@example.com
                        initials: J
                        profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                    roles:
                    - id: 1
                      name: owner
                      custom: false
                    - id: 2
                      name: admin
                      custom: false
                    - id: 3
                      name: member
                      custom: false
                    - id: 4
                      name: guest
                      custom: false
                    - id: 998877
                      name: member custom
                      inherited_role: 3
                      custom: true
                    - id: 112233
                      name: admin custom
                      inherited_role: 2
                      custom: true
                    - id: 12345
                      name: guest custom
                      inherited_role: 4
                      custom: true
              example:
                team:
                  id: '333'
                  name: Team Name
                  color: '#8D00D4'
                  avatar: null
                  members:
                  - user:
                      id: 184
                      username: null
                      email: user@example.com
                      color: null
                      profilePicture: null
                      initials: G
                      role: 2
                      custom_role:
                        id: 112233
                        name: admin custom
                      last_active: null
                      date_joined: null
                      date_invited: '1583358383412'
                    invited_by:
                      id: 183
                      color: '#827718'
                      username: Jerry
                      email: jerry@example.com
                      initials: J
                      profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                  roles:
                  - id: 1
                    name: owner
                    custom: false
                  - id: 2
                    name: admin
                    custom: false
                  - id: 3
                    name: member
                    custom: false
                  - id: 4
                    name: guest
                    custom: false
                  - id: 998877
                    name: member custom
                    inherited_role: 3
                    custom: true
                  - id: 112233
                    name: admin custom
                    inherited_role: 2
                    custom: true
                  - id: 12345
                    name: guest custom
                    inherited_role: 4
                    custom: true
      deprecated: false
  /v2/team/{team_id}/user/{user_id}:
    parameters: []
    get:
      summary: Get User
      tags:
      - Users
      description: 'View information about a user in a Workspace. \

        \

        ***Note:** This endpoint is only available to Workspaces on our Enterprise Plan.*'
      operationId: GetUser
      parameters:
      - name: team_id
        in: path
        description: Workspace ID
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 123
      - name: user_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 403
      - name: include_shared
        in: query
        description: Exclude details of items shared with the guest by setting this parameter to `false`. By default this parameter is set to `true`.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          examples:
          - false
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                title: GetUserresponse
                type: object
                properties:
                  member:
                    title: Member7
                    type: object
                    properties:
                      user:
                        title: User21
                        type: object
                        properties:
                          id:
                            type: integer
                            contentEncoding: int32
                          username:
                            type: string
                          email:
                            type: string
                          color:
                            type:
                            - string
                            - 'null'
                          profilePicture:
                            type:
                            - string
                            - 'null'
                          initials:
                            type: string
                          role:
                            description: Owner = 1, Admin = 2, Member = 3, Guest = 4
                            type: integer
                            contentEncoding: int32
                          custom_role:
                            title: CustomRole
                            required:
                            - id
                            - name
                            type: object
                            properties:
                              id:
                                type: integer
                                contentEncoding: int32
                              name:
                                type: string
                            examples:
                            - id: 12345
                              name: guest custom
                          last_active:
                            type:
                            - string
                            - 'null'
                          date_joined:
                            type:
                            - string
                            - 'null'
                          date_invited:
                            type: string
                        examples:
                        - id: 184
                          username: User Name
                          email: user@example.com
                          color: null
                          profilePicture: null
                          initials: G
                          role: 3
                          custom_role:
                            id: 998877
                            name: member custom
                          last_active: null
                          date_joined: null
                          date_invited: '1583358383412'
                      invited_by:
                        title: InvitedBy
                        type: object
                        properties:
                          id:
                            type: integer
                            contentEncoding: int32
                          color:
                            type: string
                          username:
                            type: string
                          email:
                            type: string
                          initials:
                            type: string
                          profilePicture:
                            type: string
                        examples:
                        - id: 183
                          color: '#827718'
                          username: Jerry
                          email: jerry@example.com
                          initials: J
                          profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                      shared:
                        title: Shared
                        type: object
                        properties:
                          tasks:
                            type: array
                            items:
                              type: string
                            description: ''
                          lists:
                            type: array
                            items:
                              type: string
                            description: ''
                          folders:
                            type: array
                            items:
                              type: string
                            description: ''
                        examples:
                        - tasks: []
                          lists: []
                          folders: []
                    examples:
                    - user:
                        id: 184
                        username: User Name
                        email: user@example.com
                        color: null
                        profilePicture: null
                        initials: UN
                        role: 3
                        custom_role:
                          id: 998877
                          name: member custom
                        last_active: null
                        date_joined: null
                        date_invited: '1583358383412'
                      invited_by:
                        id: 183
                        color: '#827718'
                        username: Jerry
                        email: jerry@example.com
                        initials: J
                        profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                      shared:
                        tasks: []
                        lists: []
                        folders: []
                examples:
                - member:
                    user:
                      id: 184
                      username: User Name
                      email: user@example.com
                      color: null
                      profilePicture: null
                      initials: UN
                      role: 3
                      custom_role:
                        id: 998877
                        name: member custom
                      last_active: null
                      date_joined: null
                      date_invited: '1583358383412'
                    invited_by:
                      id: 183
                      color: '#827718'
                      username: Jerry
                      email: jerry@example.com
                      initials: J
                      profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                    shared:
                      tasks: []
                      lists: []
                      folders: []
              example:
                member:
                  user:
                    id: 184
                    username: User Name
                    email: user@example.com
                    color: null
                    profilePicture: null
                    initials: UN
                    role: 3
                    custom_role:
                      id: 998877
                      name: member custom
                    last_active: '1688667338000'
                    date_joined: '1657131338000'
                    date_invited: '1657044938000'
                  invited_by:
                    id: 183
                    username: Jerry
                    color: '#827718'
                    email: jerry@example.com
                    initials: J
                    profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                  shared:
                    tasks: []
                    lists: []
                    folders: []
      deprecated: false
    put:
      summary: Edit User On Workspace
      tags:
      - Users
      description: 'Update a user''s name and role. \

        \

        ***Note:** This endpoint is only available to Workspaces on our Enterprise Plan.*'
      operationId: EditUserOnWorkspace
      parameters:
      - name: team_id
        in: path
        description: Workspace ID
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 123
      - name: user_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 403
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              title: EditUserOnWorkspacerequest
              required:
              - username
              - admin
              - custom_role_id
              type: object
              properties:
                username:
                  type: string
                admin:
                  type: boolean
                custom_role_id:
                  type: integer
                  contentEncoding: int32
              examples:
              - username: User Name
                admin: false
                custom_role_id: 998877
            example:
              username: User Name
              admin: false
              custom_role_id: 998877
        required: true
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                title: EditUserOnWorkspaceresponse
                required:
                - member
                type: object
                properties:
                  member:
                    $ref: '#/paths/~1v2~1team~1{team_id}~1user~1{user_id}/get/responses/200/content/application~1json/schema/properties/member'
                examples:
                - member:
                    user:
                      id: 184
                      username: User Name
                      email: user@example.com
                      color: null
                      profilePicture: null
                      initials: UN
                      role: 3
                      custom_role:
                        id: 998877
                        name: member custom
                      last_active: null
                      date_joined: null
                      date_invited: '1583358383412'
                    invited_by:
                      id: 183
                      color: '#827718'
                      username: Jerry
                      email: jerry@example.com
                      initials: J
                      profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                    shared:
                      tasks: []
                      lists: []
                      folders: []
              example:
                member:
                  user:
                    id: 184
                    username: User Name
                    email: user@example.com
                    color: null
                    profilePicture: null
                    initials: G
                    role: 3
                    custom_role:
                      id: 998877
                      name: member custom
                    last_active: null
                    date_joined: null
                    date_invited: '1583358383412'
                  invited_by:
                    id: 183
                    color: '#827718'
                    username: Jerry
                    email: jerry@example.com
                    initials: J
                    profilePicture: https://attachments.clickup.com/profilePictures/profile.jpg
                  shared:
                    tasks: []
                    lists: []
                    folders: []
      deprecated: false
    delete:
      summary: Remove User From Workspace
      tags:
      - Users
      description: 'Deactivate a user from a Workspace. \

        \

        ***Note:** This endpoint is only available to Workspaces on our Enterprise Plan.*'
      operationId: RemoveUserFromWorkspace
      parameters:
      - name: team_id
        in: path
        description: Workspace ID
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 123
      - name: user_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: number
          contentEncoding: double
          examples:
          - 403
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                title: RemoveUserFromWorkspaceresponse
                required:
                - team
                type: object
                properties:
                  team:
                    title: Team2
                    required:
                    - id
                    - name
                    - color
                    - avatar
                    - members
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      color:
                        type: string
                      avatar:
                        type:
                        - string
                        - 'null'
                      members:
                        type: array
                        items:
                          type: string
                        description: ''
                    examples:
                    - id: '333'
                      name: Team Name
                      color: '#8D00D4'
                      avatar: null
                      members: []
                examples:
                - team:
                    id: '333'
                    name: Team Name
                    color: '#8D00D4'
                    avatar: null
                    members: []
              example:
                team:
                  id: '333'
                  name: Team Name
                  color: '#8D00D4'
                  avatar: null
                  members: []
      deprecated: false
components:
  securitySchemes:
    Authorization_Token:
      name: Authorization
      type: apiKey
      in: header
      description: 'API token required for authentication. Two types of tokens are supported:

        **Personal API Key** Obtain from ClickUp''s settings page under ''Apps'' and add it to the header as `Authorization: pk_...`

        **OAuth2 Access Token** Generated through the OAuth2 flow and add it to the header as `Authorization: Bearer {access_token}`'
